export const ADD_MYLOCATION = "ADD_MYLOCATION"
export const DEL_MYLOCATION = "DEL_MYLOCATION"
export const EDT_MYLOCATION = "EDT_MYLOCATION"

export const ADD_LOCATIONS = "ADD_LOCATIONS"
export const DEL_LOCATIONS = "DEL_LOCATIONS"
export const EDT_LOCATIONS = "EDT_LOCATIONS"

export const GET_USER = 'GET_USER'
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED'
export const GET_USER_REJECTED = 'GET_USER_REJECTED'

export const ADD_IMAGES = "ADD_IMAGES"
export const DEL_IMAGES = "DEL_IMAGES"
export const EDT_IMAGES = "EDT_IMAGES"

export const GET_FILES = 'GET_FILES'
export const GET_FILES_OK = 'GET_FILES_OK'
export const GET_FILES_FULFILLED = 'GET_FILES_FULFILLED'
export const GET_FILES_REJECTED = 'GET_FILES_REJECTED'
export const DEL_FILES = 'DEL_FILES'
export const CLR_FILES = 'CLR_FILES'

export const GET_CHATLIST = 'GET_CHATLIST'
export const GET_CHATLIST_FULFILLED = 'GET_CHATLIST_FULFILLED'
export const GET_CHATLIST_REJECTED = 'GET_CHATLIST_REJECTED'
export const ADD_CHATS = 'GET_CHATS'

export const GET_ROOMS = 'GET_ROOMS'
export const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED'
export const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED'
export const ADD_ROOM = 'ADD_ROOM'